language: cpp

matrix:
  include:
    - os: linux
        compiler: gcc
        addons:
            apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - g++-5
        env: COMPILER=g++-5

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --config Release
  - ctest --output-on-failure -C Release