environment:
  matrix:
    - BUILD_TYPE: cmake
      VS_VERSION: Visual Studio 14

build_script:
  - md build
  - cd build
  - cmake ..
  - msbuild .\Solution.sln /p:Configuration=Debug
  
test_script:
  - ctest --output-on-failure -C Debug

deploy: off