environment:
  matrix:
    - BUILD_TYPE: cmake
      VS_VERSION: Visual Studio 14

build_script:
  - md build
  - cd build
  - cmake ..
  - cmake --build .
  
test_script:
  - ctest --output-on-failure -C Release

deploy: off