environment:
  matrix:
    - BUILD_TYPE: cmake
      VS_VERSION: Visual Studio 14

build_script:
  - md build
  - cd build
  - cmake ..
  - msbuild .\hello_root.sln /p:Configuration=Release
  
test_script:
  - ctest -C Release

deploy: off